### ISSUE TITLE
Crash after register in the Eclipse version

### ISSUE THREAD

**Issue by chriszeng87** [motianhuo/wechat#18]
08-17 11:05:55.993: I/Session(7537): EaseMob Server connected.
08-17 11:05:55.993: D/[Collector][Login][chat login time](7537): chat login time : 00:01:357
08-17 11:05:55.993: D/chat(7537): do start service: context:com.juns.wechat.App@420cd938
08-17 11:05:56.033: D/main(7537): 登陆聊天服务器成功！
08-17 11:05:56.063: W/Toast(7537): From com.juns.wechat, go ahead.
08-17 11:05:56.073: I/Timeline(7537): Timeline: Activity_launch_request id:com.juns.wechat time:83766225
08-17 11:05:56.083: D/AndroidRuntime(7537): Shutting down VM
08-17 11:05:56.083: W/dalvikvm(7537): threadid=1: thread exiting with uncaught exception (group=0x416f9d58)
08-17 11:05:56.083: E/AndroidRuntime(7537): FATAL EXCEPTION: main
08-17 11:05:56.083: E/AndroidRuntime(7537): Process: com.juns.wechat, PID: 7537
08-17 11:05:56.083: E/AndroidRuntime(7537): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.juns.wechat/com.juns.wechat.view.activity.EditUserNameActivity}; have you declared this activity in your AndroidManifest.xml?
08-17 11:05:56.083: E/AndroidRuntime(7537): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1628)
08-17 11:05:56.083: E/AndroidRuntime(7537): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
08-17 11:05:56.083: E/AndroidRuntime(7537): 	at android.app.Activity.startActivityForResult(Activity.java:3442)
08-17 11:05:56.083: E/AndroidRuntime(7537): 	at android.app.Activity.startActivityForResult(Activity.java:3403)
08-17 11:05:56.083: E/AndroidRuntime(7537): 	at android.app.Activity.startActivity(Activity.java:3645)
08-17 11:05:56.083: E/AndroidRuntime(7537): 	at android.app.Activity.startActivity(Activity.java:3613)
08-17 11:05:56.083: E/AndroidRuntime(7537): 	at com.juns.wechat.view.activity.RegisterActivity$2$1.run(RegisterActivity.java:169)
08-17 11:05:56.083: E/AndroidRuntime(7537): 	at android.os.Handler.handleCallback(Handler.java:733)
08-17 11:05:56.083: E/AndroidRuntime(7537): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-17 11:05:56.083: E/AndroidRuntime(7537): 	at android.os.Looper.loop(Looper.java:136)
08-17 11:05:56.083: E/AndroidRuntime(7537): 	at android.app.ActivityThread.main(ActivityThread.java:5047)
08-17 11:05:56.083: E/AndroidRuntime(7537): 	at java.lang.reflect.Method.invokeNative(Native Method)
08-17 11:05:56.083: E/AndroidRuntime(7537): 	at java.lang.reflect.Method.invoke(Method.java:515)
08-17 11:05:56.083: E/AndroidRuntime(7537): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
08-17 11:05:56.083: E/AndroidRuntime(7537): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
08-17 11:05:56.083: E/AndroidRuntime(7537): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by chriszeng87** [comment]
Another crash:

08-17 11:12:40.303: I/Session(8485): EaseMob Server connected.
08-17 11:12:40.303: D/[Collector][Login][chat login time](8485): chat login time : 00:05:852
08-17 11:12:40.443: D/dalvikvm(8485): GC_FOR_ALLOC freed 6169K, 29% free 16058K/22368K, paused 55ms, total 55ms
08-17 11:12:40.453: W/CursorWrapperInner(8485): Cursor finalized without prior close()
08-17 11:12:40.453: W/CursorWrapperInner(8485): Cursor finalized without prior close()
08-17 11:12:45.033: D/AndroidRuntime(8485): Shutting down VM
08-17 11:12:45.033: W/dalvikvm(8485): threadid=1: thread exiting with uncaught exception (group=0x416f9d58)
08-17 11:12:45.043: E/AndroidRuntime(8485): FATAL EXCEPTION: main
08-17 11:12:45.043: E/AndroidRuntime(8485): Process: com.juns.wechat, PID: 8485
08-17 11:12:45.043: E/AndroidRuntime(8485): java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=1
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at java.lang.String.startEndAndLength(String.java:588)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at java.lang.String.substring(String.java:1475)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at com.juns.wechat.adpter.ContactAdapter.getView(ContactAdapter.java:61)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.AbsListView.obtainView(AbsListView.java:2257)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.ListView.makeAndAddView(ListView.java:1790)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.ListView.fillDown(ListView.java:691)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.ListView.fillFromTop(ListView.java:752)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.ListView.layoutChildren(ListView.java:1630)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.AbsListView.onLayout(AbsListView.java:2089)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.View.layout(View.java:14845)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.View.layout(View.java:14845)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.View.layout(View.java:14845)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.View.layout(View.java:14845)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.View.layout(View.java:14845)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.View.layout(View.java:14845)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.View.layout(View.java:14845)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.View.layout(View.java:14845)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.View.layout(View.java:14845)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.View.layout(View.java:14845)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2026)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1783)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1039)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5648)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.Choreographer.doFrame(Choreographer.java:544)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.os.Handler.handleCallback(Handler.java:733)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.os.Looper.loop(Looper.java:136)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at android.app.ActivityThread.main(ActivityThread.java:5047)
08-17 11:12:45.043: E/AndroidRuntime(8485): 	at java.lang.re
08-17 11:12:47.953: I/Process(8485): Sending signal. PID: 8485 SIG: 9
08-17 11:12:57.213: I/chatservice(8598): chat service created

**Comment by rahulbambale** [comment]
pls friend tell me how to setup wechat application.
